# Tree type (e.g. oak), log, leaf, and grow_method all correspond to enums. They're case insensitive, which is
# demonstrated in this config.
#
# Tree types:
# - OAK
# - SPRUCE
# - BIRCH
# - JUNGLE
# - ACACIA
# - DARK_OAK
# - CRIMSON
# - WARPED
#
# Grow methods:
# - BONEMEAL
# - NATURAL
# - BOTH
#
# Chance isn't a percentage, think of it as a weight.
#
# If no tree configuration is present for a particular type & grow method, the default tree will be generated.
trees:
  oak:
    - log: COBBLESTONE
      leaf: GLASS
      chance: 100
      grow_method: both
  spruce:
    - log: STONE
      leaf: GLASS
      chance: 100
      grow_method: both
  birch:
    - log: BEDROCK
      leaf: GLASS
      chance: 100
      grow_method: both
  jungle:
    - log: OBSIDIAN
      leaf: GLASS
      chance: 100
      grow_method: both
  acacia:
    - log: GRASS_BLOCK
      leaf: GLASS
      chance: 100
      grow_method: both
  dark_oak:
    - log: GOLD_ORE
      leaf: GLASS
      chance: 100
      grow_method: both
  crimson:
    - log: TERRACOTTA
      leaf: GLASS
      chance: 100
      grow_method: both
  warped:
    - log: SANDSTONE
      leaf: GLASS
      chance: 100
      grow_method: both
enabled_worlds:
  - "world"
  - "world_nether"
  - "world_the_end"